#!/bin/sh

#
# Installation script for schema product
#

cd `dirname $0` && . ./Configuration

#
# Create symbolic links.
#
for i in table key index procedure comments
do
    cd $i
    rm -rf Configuration logs
    ln -s ../Configuration .
    ln -s ../logs/$i logs
    cd ..
done

mkdir -p ${EXPORTDATA}
mkdir -p ${EXPORTLOGS}

